version: '3'
services:
  tutorships:
    container_name: backend
    restart: always
    build: .
    ports:
      - '5001:5001'
    links:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db: 
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
    logging:
      driver: none
